# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=b'', max_length=200)),
                ('snap_link', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=b'', max_length=100)),
                ('phone', models.CharField(default=b'', max_length=11)),
                ('picture', models.ImageField(upload_to=b'profile_images')),
                ('visit', models.IntegerField(default=0)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
