# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180420_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaplink',
            name='user',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
