# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180420_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaplink',
            name='snap_link',
            field=models.URLField(),
        ),
    ]
