# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180420_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaplink',
            name='notify_me_type',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
