# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_snaplink_notify_me_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaplink',
            name='notify_me_type',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
