# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180421_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaplink',
            name='notify_me_type',
            field=models.CharField(default=b'None', max_length=200),
        ),
    ]
