# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180421_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaplink',
            name='exact_price',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='snaplink',
            name='percentage',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
