# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180425_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaplink',
            name='exact_price',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snaplink',
            name='percentage',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
    ]
